export const FETCH_DICE = "FETCH_DICE";
export const UPDATE_DICE = "UPDATE_DICE";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const UPDATE_TURN = "UPDATE_TURN";
export const NUM_PLAYERS = "NUM_PLAYERS";
export const TOGGLE_HIGHLIGHTED = "TOGGLED_HIGHLIGHTED";